project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

website:
  title: "Brett R. Bessen"
  description: "Brett R. Bessen is a political scientist at Tecnológico de Monterrey studying democratic backsliding, public opinion, and executive aggrandizement in comparative perspective, with a focus on Mexico and Latin America."
  open-graph: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: cv.qmd
        text: CV

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
